#include core/header.js
#include math/Vec2.js
#include math/Vec3.js
#include math/Vec4.js
#include math/Quat.js
#include math/Mat3.js
#include math/Mat4.js
#include rendering/CanvasRenderer.js
#include rendering/WebGLRenderer.js
#include rendering/WebGL2Renderer.js
#include core/Obj.js